webtalk_init -webtalk_dir /home/alex/GitHub/ip-cores/project/ofdm_baseband/ofdm_baseband.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-05-25 12:23:32" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cci17uqbcgusdf1o3j5f99h0jf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.4_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1163.538 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1527242635000" -context "sdk\\\\hardware/1527242635000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1527242635000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1527242635000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1527242635000"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.4" -context "sdk\\\\hardware/1527242635000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1527242635000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1527242635000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1527242635000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1527242635000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1527242635000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1527242635000"
webtalk_add_data -client sdk -key uid -value "1527242715000" -context "sdk\\\\bsp/1527242715000"
webtalk_add_data -client sdk -key hwid -value "1527242635000" -context "sdk\\\\bsp/1527242715000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1527242715000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1527242715000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1527242715000"
webtalk_add_data -client sdk -key uid -value "1527242717000" -context "sdk\\\\application/1527242717000"
webtalk_add_data -client sdk -key hwid -value "1527242635000" -context "sdk\\\\application/1527242717000"
webtalk_add_data -client sdk -key bspid -value "1527242715000" -context "sdk\\\\application/1527242717000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1527242717000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1527242717000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1527242717000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1527242717000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1527242717000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1527242717000"
webtalk_add_data -client sdk -key projSize -value "225.23046875" -context "sdk\\\\application/1527242717000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1527247412586"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1527247412586"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1527247412586"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1527247412586"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1527247412586"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1527247412586"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1527247412586"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1527247412586"
webtalk_transmit -clientid 959749345 -regid "" -xml /home/alex/GitHub/ip-cores/project/ofdm_baseband/ofdm_baseband.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/alex/GitHub/ip-cores/project/ofdm_baseband/ofdm_baseband.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/alex/GitHub/ip-cores/project/ofdm_baseband/ofdm_baseband.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
