webtalk_init -webtalk_dir /home/alex/GitHub/ip-cores/project/ofdm_baseband/ofdm_baseband.sim/sim_1/behav/xsim.dir/baseband_tb_load_file_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May  9 22:23:17 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1756540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "05a21977aa9357a98c3cc6d0ff549e93" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8b2ffa7887c14a659170f0d8e4a4559e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3838.124 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "56075 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "22" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "13.37_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "136816_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4248052998 -regid "" -xml /home/alex/GitHub/ip-cores/project/ofdm_baseband/ofdm_baseband.sim/sim_1/behav/xsim.dir/baseband_tb_load_file_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/alex/GitHub/ip-cores/project/ofdm_baseband/ofdm_baseband.sim/sim_1/behav/xsim.dir/baseband_tb_load_file_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/alex/GitHub/ip-cores/project/ofdm_baseband/ofdm_baseband.sim/sim_1/behav/xsim.dir/baseband_tb_load_file_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
